// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testP.proto

package com.htsc.yang.proto;

public final class TestP {
  private TestP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.htsc.yang.proto.a1}
   */
  public enum a1
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>a = 1;</code>
     */
    a(1),
    /**
     * <code>b = 2;</code>
     */
    b(2),
    /**
     * <code>c = 3;</code>
     */
    c(3),
    ;

    /**
     * <code>a = 1;</code>
     */
    public static final int a_VALUE = 1;
    /**
     * <code>b = 2;</code>
     */
    public static final int b_VALUE = 2;
    /**
     * <code>c = 3;</code>
     */
    public static final int c_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static a1 valueOf(int value) {
      return forNumber(value);
    }

    public static a1 forNumber(int value) {
      switch (value) {
        case 1: return a;
        case 2: return b;
        case 3: return c;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<a1>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        a1> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<a1>() {
            public a1 findValueByNumber(int number) {
              return a1.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.htsc.yang.proto.TestP.getDescriptor().getEnumTypes().get(0);
    }

    private static final a1[] VALUES = values();

    public static a1 valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private a1(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.htsc.yang.proto.a1)
  }

  public interface TestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.htsc.yang.proto.TestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *为optional 字段指定默认值
     * </pre>
     *
     * <code>optional uint32 sex = 3 [default = 10];</code>
     */
    boolean hasSex();
    /**
     * <pre>
     *为optional 字段指定默认值
     * </pre>
     *
     * <code>optional uint32 sex = 3 [default = 10];</code>
     */
    int getSex();

    /**
     * <code>optional .com.htsc.yang.proto.TestMessage.Corpus corpus = 4 [default = UNIVERSAL];</code>
     */
    boolean hasCorpus();
    /**
     * <code>optional .com.htsc.yang.proto.TestMessage.Corpus corpus = 4 [default = UNIVERSAL];</code>
     */
    com.htsc.yang.proto.TestP.TestMessage.Corpus getCorpus();

    /**
     * <code>optional .com.htsc.yang.proto.a1 tt = 5;</code>
     */
    boolean hasTt();
    /**
     * <code>optional .com.htsc.yang.proto.a1 tt = 5;</code>
     */
    com.htsc.yang.proto.TestP.a1 getTt();
  }
  /**
   * Protobuf type {@code com.htsc.yang.proto.TestMessage}
   */
  public  static final class TestMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.htsc.yang.proto.TestMessage)
      TestMessageOrBuilder {
    // Use TestMessage.newBuilder() to construct.
    private TestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TestMessage() {
      id_ = 0L;
      name_ = "";
      sex_ = 10;
      corpus_ = 0;
      tt_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sex_ = input.readUInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.htsc.yang.proto.TestP.TestMessage.Corpus value = com.htsc.yang.proto.TestP.TestMessage.Corpus.forNumber(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                corpus_ = rawValue;
              }
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.htsc.yang.proto.TestP.a1 value = com.htsc.yang.proto.TestP.a1.forNumber(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                tt_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_TestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_TestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.htsc.yang.proto.TestP.TestMessage.class, com.htsc.yang.proto.TestP.TestMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code com.htsc.yang.proto.TestMessage.Corpus}
     */
    public enum Corpus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNIVERSAL = 0;</code>
       */
      UNIVERSAL(0),
      /**
       * <code>WEB = 1;</code>
       */
      WEB(1),
      /**
       * <code>IMAGES = 2;</code>
       */
      IMAGES(2),
      /**
       * <code>LOCAL = 3;</code>
       */
      LOCAL(3),
      /**
       * <code>NEWS = 4;</code>
       */
      NEWS(4),
      /**
       * <code>PRODUCTS = 5;</code>
       */
      PRODUCTS(5),
      /**
       * <code>VIDEO = 6;</code>
       */
      VIDEO(6),
      ;

      /**
       * <code>UNIVERSAL = 0;</code>
       */
      public static final int UNIVERSAL_VALUE = 0;
      /**
       * <code>WEB = 1;</code>
       */
      public static final int WEB_VALUE = 1;
      /**
       * <code>IMAGES = 2;</code>
       */
      public static final int IMAGES_VALUE = 2;
      /**
       * <code>LOCAL = 3;</code>
       */
      public static final int LOCAL_VALUE = 3;
      /**
       * <code>NEWS = 4;</code>
       */
      public static final int NEWS_VALUE = 4;
      /**
       * <code>PRODUCTS = 5;</code>
       */
      public static final int PRODUCTS_VALUE = 5;
      /**
       * <code>VIDEO = 6;</code>
       */
      public static final int VIDEO_VALUE = 6;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Corpus valueOf(int value) {
        return forNumber(value);
      }

      public static Corpus forNumber(int value) {
        switch (value) {
          case 0: return UNIVERSAL;
          case 1: return WEB;
          case 2: return IMAGES;
          case 3: return LOCAL;
          case 4: return NEWS;
          case 5: return PRODUCTS;
          case 6: return VIDEO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Corpus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Corpus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Corpus>() {
              public Corpus findValueByNumber(int number) {
                return Corpus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.htsc.yang.proto.TestP.TestMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Corpus[] VALUES = values();

      public static Corpus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Corpus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.htsc.yang.proto.TestMessage.Corpus)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <pre>
     *为optional 字段指定默认值
     * </pre>
     *
     * <code>optional uint32 sex = 3 [default = 10];</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *为optional 字段指定默认值
     * </pre>
     *
     * <code>optional uint32 sex = 3 [default = 10];</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int CORPUS_FIELD_NUMBER = 4;
    private int corpus_;
    /**
     * <code>optional .com.htsc.yang.proto.TestMessage.Corpus corpus = 4 [default = UNIVERSAL];</code>
     */
    public boolean hasCorpus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.htsc.yang.proto.TestMessage.Corpus corpus = 4 [default = UNIVERSAL];</code>
     */
    public com.htsc.yang.proto.TestP.TestMessage.Corpus getCorpus() {
      com.htsc.yang.proto.TestP.TestMessage.Corpus result = com.htsc.yang.proto.TestP.TestMessage.Corpus.forNumber(corpus_);
      return result == null ? com.htsc.yang.proto.TestP.TestMessage.Corpus.UNIVERSAL : result;
    }

    public static final int TT_FIELD_NUMBER = 5;
    private int tt_;
    /**
     * <code>optional .com.htsc.yang.proto.a1 tt = 5;</code>
     */
    public boolean hasTt() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.htsc.yang.proto.a1 tt = 5;</code>
     */
    public com.htsc.yang.proto.TestP.a1 getTt() {
      com.htsc.yang.proto.TestP.a1 result = com.htsc.yang.proto.TestP.a1.forNumber(tt_);
      return result == null ? com.htsc.yang.proto.TestP.a1.a : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, corpus_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, tt_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, corpus_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, tt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.htsc.yang.proto.TestP.TestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.htsc.yang.proto.TestP.TestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.TestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.htsc.yang.proto.TestP.TestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.TestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.htsc.yang.proto.TestP.TestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.TestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.htsc.yang.proto.TestP.TestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.htsc.yang.proto.TestP.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.htsc.yang.proto.TestP.TestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.htsc.yang.proto.TestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.htsc.yang.proto.TestMessage)
        com.htsc.yang.proto.TestP.TestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_TestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_TestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.htsc.yang.proto.TestP.TestMessage.class, com.htsc.yang.proto.TestP.TestMessage.Builder.class);
      }

      // Construct using com.htsc.yang.proto.TestP.TestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sex_ = 10;
        bitField0_ = (bitField0_ & ~0x00000004);
        corpus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        tt_ = 1;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_TestMessage_descriptor;
      }

      public com.htsc.yang.proto.TestP.TestMessage getDefaultInstanceForType() {
        return com.htsc.yang.proto.TestP.TestMessage.getDefaultInstance();
      }

      public com.htsc.yang.proto.TestP.TestMessage build() {
        com.htsc.yang.proto.TestP.TestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.htsc.yang.proto.TestP.TestMessage buildPartial() {
        com.htsc.yang.proto.TestP.TestMessage result = new com.htsc.yang.proto.TestP.TestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.corpus_ = corpus_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.tt_ = tt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.htsc.yang.proto.TestP.TestMessage) {
          return mergeFrom((com.htsc.yang.proto.TestP.TestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.htsc.yang.proto.TestP.TestMessage other) {
        if (other == com.htsc.yang.proto.TestP.TestMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasCorpus()) {
          setCorpus(other.getCorpus());
        }
        if (other.hasTt()) {
          setTt(other.getTt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.htsc.yang.proto.TestP.TestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.htsc.yang.proto.TestP.TestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int sex_ = 10;
      /**
       * <pre>
       *为optional 字段指定默认值
       * </pre>
       *
       * <code>optional uint32 sex = 3 [default = 10];</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *为optional 字段指定默认值
       * </pre>
       *
       * <code>optional uint32 sex = 3 [default = 10];</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <pre>
       *为optional 字段指定默认值
       * </pre>
       *
       * <code>optional uint32 sex = 3 [default = 10];</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000004;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *为optional 字段指定默认值
       * </pre>
       *
       * <code>optional uint32 sex = 3 [default = 10];</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 10;
        onChanged();
        return this;
      }

      private int corpus_ = 0;
      /**
       * <code>optional .com.htsc.yang.proto.TestMessage.Corpus corpus = 4 [default = UNIVERSAL];</code>
       */
      public boolean hasCorpus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.htsc.yang.proto.TestMessage.Corpus corpus = 4 [default = UNIVERSAL];</code>
       */
      public com.htsc.yang.proto.TestP.TestMessage.Corpus getCorpus() {
        com.htsc.yang.proto.TestP.TestMessage.Corpus result = com.htsc.yang.proto.TestP.TestMessage.Corpus.forNumber(corpus_);
        return result == null ? com.htsc.yang.proto.TestP.TestMessage.Corpus.UNIVERSAL : result;
      }
      /**
       * <code>optional .com.htsc.yang.proto.TestMessage.Corpus corpus = 4 [default = UNIVERSAL];</code>
       */
      public Builder setCorpus(com.htsc.yang.proto.TestP.TestMessage.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        corpus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.htsc.yang.proto.TestMessage.Corpus corpus = 4 [default = UNIVERSAL];</code>
       */
      public Builder clearCorpus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        corpus_ = 0;
        onChanged();
        return this;
      }

      private int tt_ = 1;
      /**
       * <code>optional .com.htsc.yang.proto.a1 tt = 5;</code>
       */
      public boolean hasTt() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.htsc.yang.proto.a1 tt = 5;</code>
       */
      public com.htsc.yang.proto.TestP.a1 getTt() {
        com.htsc.yang.proto.TestP.a1 result = com.htsc.yang.proto.TestP.a1.forNumber(tt_);
        return result == null ? com.htsc.yang.proto.TestP.a1.a : result;
      }
      /**
       * <code>optional .com.htsc.yang.proto.a1 tt = 5;</code>
       */
      public Builder setTt(com.htsc.yang.proto.TestP.a1 value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        tt_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.htsc.yang.proto.a1 tt = 5;</code>
       */
      public Builder clearTt() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tt_ = 1;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.htsc.yang.proto.TestMessage)
    }

    // @@protoc_insertion_point(class_scope:com.htsc.yang.proto.TestMessage)
    private static final com.htsc.yang.proto.TestP.TestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.htsc.yang.proto.TestP.TestMessage();
    }

    public static com.htsc.yang.proto.TestP.TestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TestMessage>
        PARSER = new com.google.protobuf.AbstractParser<TestMessage>() {
      public TestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestMessage> getParserForType() {
      return PARSER;
    }

    public com.htsc.yang.proto.TestP.TestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.htsc.yang.proto.SearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string query = 1;</code>
     */
    boolean hasQuery();
    /**
     * <code>required string query = 1;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>required string query = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>optional int32 page_number = 2;</code>
     */
    boolean hasPageNumber();
    /**
     * <code>optional int32 page_number = 2;</code>
     */
    int getPageNumber();

    /**
     * <code>optional int32 result_per_page = 3;</code>
     */
    boolean hasResultPerPage();
    /**
     * <code>optional int32 result_per_page = 3;</code>
     */
    int getResultPerPage();

    /**
     * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
     */
    boolean hasSr();
    /**
     * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
     */
    com.htsc.yang.proto.TestP.SearchResponse getSr();
    /**
     * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
     */
    com.htsc.yang.proto.TestP.SearchResponseOrBuilder getSrOrBuilder();
  }
  /**
   * Protobuf type {@code com.htsc.yang.proto.SearchRequest}
   */
  public  static final class SearchRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.htsc.yang.proto.SearchRequest)
      SearchRequestOrBuilder {
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SearchRequest() {
      query_ = "";
      pageNumber_ = 0;
      resultPerPage_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              query_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pageNumber_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              resultPerPage_ = input.readInt32();
              break;
            }
            case 34: {
              com.htsc.yang.proto.TestP.SearchResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = sr_.toBuilder();
              }
              sr_ = input.readMessage(com.htsc.yang.proto.TestP.SearchResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sr_);
                sr_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.htsc.yang.proto.TestP.SearchRequest.class, com.htsc.yang.proto.TestP.SearchRequest.Builder.class);
    }

    private int bitField0_;
    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <code>required string query = 1;</code>
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string query = 1;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          query_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string query = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
    private int pageNumber_;
    /**
     * <code>optional int32 page_number = 2;</code>
     */
    public boolean hasPageNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 page_number = 2;</code>
     */
    public int getPageNumber() {
      return pageNumber_;
    }

    public static final int RESULT_PER_PAGE_FIELD_NUMBER = 3;
    private int resultPerPage_;
    /**
     * <code>optional int32 result_per_page = 3;</code>
     */
    public boolean hasResultPerPage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 result_per_page = 3;</code>
     */
    public int getResultPerPage() {
      return resultPerPage_;
    }

    public static final int SR_FIELD_NUMBER = 4;
    private com.htsc.yang.proto.TestP.SearchResponse sr_;
    /**
     * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
     */
    public boolean hasSr() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
     */
    public com.htsc.yang.proto.TestP.SearchResponse getSr() {
      return sr_ == null ? com.htsc.yang.proto.TestP.SearchResponse.getDefaultInstance() : sr_;
    }
    /**
     * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
     */
    public com.htsc.yang.proto.TestP.SearchResponseOrBuilder getSrOrBuilder() {
      return sr_ == null ? com.htsc.yang.proto.TestP.SearchResponse.getDefaultInstance() : sr_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasQuery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, query_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pageNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, resultPerPage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getSr());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, query_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resultPerPage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSr());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.htsc.yang.proto.TestP.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.htsc.yang.proto.TestP.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.htsc.yang.proto.TestP.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.htsc.yang.proto.TestP.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.htsc.yang.proto.TestP.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.htsc.yang.proto.TestP.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.htsc.yang.proto.TestP.SearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.htsc.yang.proto.SearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.htsc.yang.proto.SearchRequest)
        com.htsc.yang.proto.TestP.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.htsc.yang.proto.TestP.SearchRequest.class, com.htsc.yang.proto.TestP.SearchRequest.Builder.class);
      }

      // Construct using com.htsc.yang.proto.TestP.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSrFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        query_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pageNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        resultPerPage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (srBuilder_ == null) {
          sr_ = null;
        } else {
          srBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchRequest_descriptor;
      }

      public com.htsc.yang.proto.TestP.SearchRequest getDefaultInstanceForType() {
        return com.htsc.yang.proto.TestP.SearchRequest.getDefaultInstance();
      }

      public com.htsc.yang.proto.TestP.SearchRequest build() {
        com.htsc.yang.proto.TestP.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.htsc.yang.proto.TestP.SearchRequest buildPartial() {
        com.htsc.yang.proto.TestP.SearchRequest result = new com.htsc.yang.proto.TestP.SearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.query_ = query_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageNumber_ = pageNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.resultPerPage_ = resultPerPage_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (srBuilder_ == null) {
          result.sr_ = sr_;
        } else {
          result.sr_ = srBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.htsc.yang.proto.TestP.SearchRequest) {
          return mergeFrom((com.htsc.yang.proto.TestP.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.htsc.yang.proto.TestP.SearchRequest other) {
        if (other == com.htsc.yang.proto.TestP.SearchRequest.getDefaultInstance()) return this;
        if (other.hasQuery()) {
          bitField0_ |= 0x00000001;
          query_ = other.query_;
          onChanged();
        }
        if (other.hasPageNumber()) {
          setPageNumber(other.getPageNumber());
        }
        if (other.hasResultPerPage()) {
          setResultPerPage(other.getResultPerPage());
        }
        if (other.hasSr()) {
          mergeSr(other.getSr());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasQuery()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.htsc.yang.proto.TestP.SearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.htsc.yang.proto.TestP.SearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object query_ = "";
      /**
       * <code>required string query = 1;</code>
       */
      public boolean hasQuery() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string query = 1;</code>
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            query_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string query = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string query = 1;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 1;</code>
       */
      public Builder clearQuery() {
        bitField0_ = (bitField0_ & ~0x00000001);
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 1;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }

      private int pageNumber_ ;
      /**
       * <code>optional int32 page_number = 2;</code>
       */
      public boolean hasPageNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 page_number = 2;</code>
       */
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <code>optional int32 page_number = 2;</code>
       */
      public Builder setPageNumber(int value) {
        bitField0_ |= 0x00000002;
        pageNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page_number = 2;</code>
       */
      public Builder clearPageNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      private int resultPerPage_ ;
      /**
       * <code>optional int32 result_per_page = 3;</code>
       */
      public boolean hasResultPerPage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 result_per_page = 3;</code>
       */
      public int getResultPerPage() {
        return resultPerPage_;
      }
      /**
       * <code>optional int32 result_per_page = 3;</code>
       */
      public Builder setResultPerPage(int value) {
        bitField0_ |= 0x00000004;
        resultPerPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result_per_page = 3;</code>
       */
      public Builder clearResultPerPage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        resultPerPage_ = 0;
        onChanged();
        return this;
      }

      private com.htsc.yang.proto.TestP.SearchResponse sr_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.htsc.yang.proto.TestP.SearchResponse, com.htsc.yang.proto.TestP.SearchResponse.Builder, com.htsc.yang.proto.TestP.SearchResponseOrBuilder> srBuilder_;
      /**
       * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
       */
      public boolean hasSr() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
       */
      public com.htsc.yang.proto.TestP.SearchResponse getSr() {
        if (srBuilder_ == null) {
          return sr_ == null ? com.htsc.yang.proto.TestP.SearchResponse.getDefaultInstance() : sr_;
        } else {
          return srBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
       */
      public Builder setSr(com.htsc.yang.proto.TestP.SearchResponse value) {
        if (srBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sr_ = value;
          onChanged();
        } else {
          srBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
       */
      public Builder setSr(
          com.htsc.yang.proto.TestP.SearchResponse.Builder builderForValue) {
        if (srBuilder_ == null) {
          sr_ = builderForValue.build();
          onChanged();
        } else {
          srBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
       */
      public Builder mergeSr(com.htsc.yang.proto.TestP.SearchResponse value) {
        if (srBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              sr_ != null &&
              sr_ != com.htsc.yang.proto.TestP.SearchResponse.getDefaultInstance()) {
            sr_ =
              com.htsc.yang.proto.TestP.SearchResponse.newBuilder(sr_).mergeFrom(value).buildPartial();
          } else {
            sr_ = value;
          }
          onChanged();
        } else {
          srBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
       */
      public Builder clearSr() {
        if (srBuilder_ == null) {
          sr_ = null;
          onChanged();
        } else {
          srBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
       */
      public com.htsc.yang.proto.TestP.SearchResponse.Builder getSrBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getSrFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
       */
      public com.htsc.yang.proto.TestP.SearchResponseOrBuilder getSrOrBuilder() {
        if (srBuilder_ != null) {
          return srBuilder_.getMessageOrBuilder();
        } else {
          return sr_ == null ?
              com.htsc.yang.proto.TestP.SearchResponse.getDefaultInstance() : sr_;
        }
      }
      /**
       * <code>optional .com.htsc.yang.proto.SearchResponse sr = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.htsc.yang.proto.TestP.SearchResponse, com.htsc.yang.proto.TestP.SearchResponse.Builder, com.htsc.yang.proto.TestP.SearchResponseOrBuilder> 
          getSrFieldBuilder() {
        if (srBuilder_ == null) {
          srBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.htsc.yang.proto.TestP.SearchResponse, com.htsc.yang.proto.TestP.SearchResponse.Builder, com.htsc.yang.proto.TestP.SearchResponseOrBuilder>(
                  getSr(),
                  getParentForChildren(),
                  isClean());
          sr_ = null;
        }
        return srBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.htsc.yang.proto.SearchRequest)
    }

    // @@protoc_insertion_point(class_scope:com.htsc.yang.proto.SearchRequest)
    private static final com.htsc.yang.proto.TestP.SearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.htsc.yang.proto.TestP.SearchRequest();
    }

    public static com.htsc.yang.proto.TestP.SearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
      public SearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    public com.htsc.yang.proto.TestP.SearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.htsc.yang.proto.SearchResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.htsc.yang.proto.SearchResponse}
   */
  public  static final class SearchResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.htsc.yang.proto.SearchResponse)
      SearchResponseOrBuilder {
    // Use SearchResponse.newBuilder() to construct.
    private SearchResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SearchResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.htsc.yang.proto.TestP.SearchResponse.class, com.htsc.yang.proto.TestP.SearchResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.htsc.yang.proto.TestP.SearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.htsc.yang.proto.TestP.SearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.SearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.htsc.yang.proto.TestP.SearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.SearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.htsc.yang.proto.TestP.SearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.SearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.htsc.yang.proto.TestP.SearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.htsc.yang.proto.TestP.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.htsc.yang.proto.TestP.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.htsc.yang.proto.TestP.SearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.htsc.yang.proto.SearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.htsc.yang.proto.SearchResponse)
        com.htsc.yang.proto.TestP.SearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.htsc.yang.proto.TestP.SearchResponse.class, com.htsc.yang.proto.TestP.SearchResponse.Builder.class);
      }

      // Construct using com.htsc.yang.proto.TestP.SearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.htsc.yang.proto.TestP.internal_static_com_htsc_yang_proto_SearchResponse_descriptor;
      }

      public com.htsc.yang.proto.TestP.SearchResponse getDefaultInstanceForType() {
        return com.htsc.yang.proto.TestP.SearchResponse.getDefaultInstance();
      }

      public com.htsc.yang.proto.TestP.SearchResponse build() {
        com.htsc.yang.proto.TestP.SearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.htsc.yang.proto.TestP.SearchResponse buildPartial() {
        com.htsc.yang.proto.TestP.SearchResponse result = new com.htsc.yang.proto.TestP.SearchResponse(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.htsc.yang.proto.TestP.SearchResponse) {
          return mergeFrom((com.htsc.yang.proto.TestP.SearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.htsc.yang.proto.TestP.SearchResponse other) {
        if (other == com.htsc.yang.proto.TestP.SearchResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.htsc.yang.proto.TestP.SearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.htsc.yang.proto.TestP.SearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.htsc.yang.proto.SearchResponse)
    }

    // @@protoc_insertion_point(class_scope:com.htsc.yang.proto.SearchResponse)
    private static final com.htsc.yang.proto.TestP.SearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.htsc.yang.proto.TestP.SearchResponse();
    }

    public static com.htsc.yang.proto.TestP.SearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
      public SearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResponse> getParserForType() {
      return PARSER;
    }

    public com.htsc.yang.proto.TestP.SearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_htsc_yang_proto_TestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_htsc_yang_proto_TestMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_htsc_yang_proto_SearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_htsc_yang_proto_SearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_htsc_yang_proto_SearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_htsc_yang_proto_SearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013testP.proto\022\023com.htsc.yang.proto\"\375\001\n\013T" +
      "estMessage\022\n\n\002id\030\001 \002(\004\022\014\n\004name\030\002 \001(\t\022\017\n\003" +
      "sex\030\003 \001(\r:\00210\022B\n\006corpus\030\004 \001(\0162\'.com.htsc" +
      ".yang.proto.TestMessage.Corpus:\tUNIVERSA" +
      "L\022#\n\002tt\030\005 \001(\0162\027.com.htsc.yang.proto.a1\"Z" +
      "\n\006Corpus\022\r\n\tUNIVERSAL\020\000\022\007\n\003WEB\020\001\022\n\n\006IMAG" +
      "ES\020\002\022\t\n\005LOCAL\020\003\022\010\n\004NEWS\020\004\022\014\n\010PRODUCTS\020\005\022" +
      "\t\n\005VIDEO\020\006\"}\n\rSearchRequest\022\r\n\005query\030\001 \002" +
      "(\t\022\023\n\013page_number\030\002 \001(\005\022\027\n\017result_per_pa" +
      "ge\030\003 \001(\005\022/\n\002sr\030\004 \001(\0132#.com.htsc.yang.pro",
      "to.SearchResponse\"\020\n\016SearchResponse*\031\n\002a" +
      "1\022\005\n\001a\020\001\022\005\n\001b\020\002\022\005\n\001c\020\003B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_htsc_yang_proto_TestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_htsc_yang_proto_TestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_htsc_yang_proto_TestMessage_descriptor,
        new java.lang.String[] { "Id", "Name", "Sex", "Corpus", "Tt", });
    internal_static_com_htsc_yang_proto_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_htsc_yang_proto_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_htsc_yang_proto_SearchRequest_descriptor,
        new java.lang.String[] { "Query", "PageNumber", "ResultPerPage", "Sr", });
    internal_static_com_htsc_yang_proto_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_htsc_yang_proto_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_htsc_yang_proto_SearchResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
